package problem044;

import java.util.ArrayList;
import java.util.List;

public class Problem044 {

    /*
    Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

    1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
    */
    public static void main(String[] args) {
        
        int minj = -1;
        int mink = -1;
        int minDistance = Integer.MAX_VALUE;
        
        List<Integer> pentNums = new ArrayList<>();
        for (int i = 1; i < 10000; i++)
            pentNums.add( (3*i-1)*i/2);
        
        for (int j : pentNums) {
            for (int k : pentNums) {
                if (pentNums.contains(j+k) && pentNums.contains(k-j)) {
                    System.out.println(j + "\t" + k);
                    if (Math.abs(j-k) < minDistance) {
                        minDistance = Math.abs(j-k);
                        minj = j;
                        mink = k;
                    }
                }
            }
        }
        System.out.println(minj + "\t" + mink);
        System.out.println(minDistance);
    }
    //answer: 5482660

}
