[package]
name = "p017"
version = "0.1.0"
authors = ["Calvin Cramer <calvincramer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-math-tools = { path = "../../../libs/rust-math-tools" }
