name: project euler rust tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  main:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project-euler/problems/rust
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --release --features run_all
      
    - name: Run
      run: ./target/release/rust
